---
categories:
  open:
    name: Åbne servere
    description: Servere du kan blive medlem af med det samme, uden godkendelse.
    more: |
      Du kan oprette dig og begynde at bruge din konto med det samme. Der er ingen godkendelse eller krav du skal opfylde (udover at følge reglerne).
    admonition: success

  review:
    name: Kræver godkendelse
    description: Servere der manuelt godkender dit medlemsskab.
    more: |
      Det svinger meget fra server til server hvor hurtigt din bruger bliver godkendt, men regn med omkring 24 timer.
    admonition: note

  invite:
    name: Invitation påkrævet
    description: Servere der ikke accepterer nye medlemmer uden invitation (eller overhovedet).
    more: |
      Servere kræver ofte invitation af to årsager.

      1. Serveren har ikke kapacitet til flere brugere.
      2. Ejeren af serveren vil gerne sikre sig der ikke kommer brugere på serveren som mindst én anden på serveren kender i forvejen.
    admonition: warning

  private:
    name: Forening / private
    description: Servere der kræver medlemsskab af en forening eller opfylde andre særlige krav for at få en bruger.
    admonition: warning

servers:
  - url: https://norrebro.space
  - url: https://turingfesten.dk
  - url: https://mstdn.dk
  - url: https://helvede.net
  - url: https://expressional.social
    covenant: true
  - url: https://uddannelse.social
  - url: https://social.data.coop
    category: private

